# Generated by Django 5.0.4 on 2024-05-05 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название направления')),
            ],
            options={
                'verbose_name': 'Направление',
                'verbose_name_plural': 'Направления',
            },
        ),
        migrations.CreateModel(
            name='Social_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='социальная сеть')),
            ],
            options={
                'verbose_name': 'Социальная сеть',
                'verbose_name_plural': 'Социальные сети',
            },
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название компании')),
                ('description', models.TextField(max_length=255, verbose_name='описание стажировки')),
                ('link', models.URLField(verbose_name='ссылка на сайт')),
                ('recruitment', models.CharField(max_length=255, verbose_name='набор')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career_internship.category', verbose_name='направление')),
            ],
            options={
                'verbose_name': 'Стажировка',
                'verbose_name_plural': 'Стажировки',
            },
        ),
        migrations.CreateModel(
            name='Social_media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(verbose_name='ссылка на соцсеть')),
                ('internship_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career_internship.internship', verbose_name='стажировка')),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career_internship.social_type', verbose_name='соцсеть')),
            ],
            options={
                'verbose_name': 'Cсылка на соцсети',
                'verbose_name_plural': 'Ссылки на соцсети',
            },
        ),
    ]
