# Generated by Django 5.0.4 on 2024-05-17 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_internship', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название компании')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
        migrations.RemoveField(
            model_name='social_media',
            name='internship_id',
        ),
        migrations.RemoveField(
            model_name='social_media',
            name='type_id',
        ),
        migrations.DeleteModel(
            name='Internship',
        ),
        migrations.DeleteModel(
            name='Social_media',
        ),
        migrations.DeleteModel(
            name='Social_type',
        ),
    ]
