# Generated by Django 5.0.4 on 2024-05-17 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_internship', '0002_company_remove_social_media_internship_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='социальная сеть')),
            ],
            options={
                'verbose_name': 'Социальная сеть',
                'verbose_name_plural': 'Социальные сети',
            },
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=255, verbose_name='описание стажировки')),
                ('link', models.URLField(verbose_name='ссылка на сайт')),
                ('recruitment', models.CharField(max_length=255, verbose_name='набор')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career_internship.category', verbose_name='направление')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career_internship.company', verbose_name='компания')),
            ],
            options={
                'verbose_name': 'Стажировка',
                'verbose_name_plural': 'Стажировки',
            },
        ),
        migrations.CreateModel(
            name='Social_media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(verbose_name='ссылка на соцсеть')),
                ('internship_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career_internship.internship', verbose_name='стажировка')),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career_internship.social_type', verbose_name='соцсеть')),
            ],
            options={
                'verbose_name': 'Cсылка на соцсети',
                'verbose_name_plural': 'Ссылки на соцсети',
            },
        ),
    ]
