# Generated by Django 5.0.4 on 2024-05-17 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career_internship', '0003_social_type_internship_social_media'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Social_media',
        ),
    ]
