# Generated by Django 5.0.4 on 2024-05-17 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_internship', '0004_delete_social_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social_media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(verbose_name='ссылка на соцсеть')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career_internship.company', verbose_name='стажировка')),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career_internship.social_type', verbose_name='соцсеть')),
            ],
            options={
                'verbose_name': 'Cсылка на соцсети',
                'verbose_name_plural': 'Ссылки на соцсети',
            },
        ),
    ]
